x-common-variables: &common-variables
  PUID: 1000
  PGID: 973
  TZ: Etc/UTC

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      <<: *common-variables
      GF_SERVER_ROOT_URL: http://grafana.thecowsaysmoo.net/
      GF_INSTALL_PLUGINS: |-
        grafana-clock-panel, 
        grafana-piechart-panel, 
        grafana-github-datasource,
        yesoreyeram-infinity-datasource
    user: "0"
    networks:
      - grafana
      - backend
    ports:
      - 4000:3000
    volumes:
      - /opt/docker/grafana/data:/var/lib/grafana
      - /opt/docker/grafana/config:/etc/grafana
    restart: unless-stopped
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command:
      - '-housekeeping_interval=5s'
      - '-docker_only=true'
    networks:
      - grafana
      - backend
    ports:
      - 9080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    devices:
      - /dev/kmsg

networks:
  grafana:
    name: grafana
  backend:
    name: backend
    external: true
